### PR TITLE
Add fourth lecture draft

### PR DESCRIPTION
**Pull request by joelostblom**
I included all the output in the notebook so that it is easy to view and comment here.

### CODE REVIEW

**Comment by joelostblom** [comment]
@SaraMati I added some new material, let me know what you think!

**Comment by linamnt** [comment]
What you have looks great, thanks for all the work you're putting in to convert the material :)
I think it's quite a lot of material to go through in 3hrs so perhaps what you have converted to Python already seems quite enough? It might be a lot to have students wrap their heads around the "why" of good plotting, as well as "how" all in 2hrs (assuming the first long/wide data in pandas takes about an hour).

**Comment by joelostblom** [comment]
@linamnt Thanks! Yes, you're right, we don't want it to be rushed through because it is too much, then no one learns anything... The last section on color can be skipped if we are low on time, and maybe some challenges also.

I did my final big update just now, basically moving sections around, removing some and filling out others. It should read well now and be ready for the workshop apart from me fixing the challenge (which I will do later).

@SaraMati Do you want to read through it and see if my time estimates are suitable and add the heatmap matrix plot if you have extra time (or want to replace a section with it).

**Comment by SaraMati** [comment]
@joelostblom yes, but I only get to finish it tonight after the Coders session :( I hope it's not too late, is it?

**Comment by joelostblom** [comment]
@SaraMati Sounds good!

**Pull request merged**
