### PR TITLE
Add third lecture draft

### PR DESCRIPTION
**Pull request by joelostblom**
I included all the output in the notebook so that it is easy to view and comment here.

### CODE REVIEW

**Comment by linamnt** [comment]
Will look in more detail later this week, but on the topic of lambda. I personally think lambda is a difficult one to teach in this context, they only recently learned what a function is and maybe still need to feel more comfortable with that before lambda? That's my opinion though, happy to teach it otherwise.

**Comment by joelostblom** [comment]
Yes, that's what I was thinking as well. It only popped up in my head
because of using `assign()` to rename columns, but that is probably
unnecessary complicated and much clearer if we do it in a separate step.

**Comment by joelostblom** [comment]
@linamnt This should now be pretty much ready to go for the workshop aside from the challenges which I will fix later. Please have a look and if you like it, try to work through it roughly to see if the time estimates are reasonable.

**Comment by linamnt** [comment]
I went through and it looks like should be a good amount for 2.5 hrs + maybe 1/2 hr for challenges! If anything, I might have to quickly skim over facetting or skip.

**Comment by joelostblom** [comment]
Thanks @linamnt. I am considering moving the split apply combine section (or half of it) to the previous lecture. I don't want you to feel like you have to skip things, and especially not the parts that might require additional time for the students to understand. I'll send an email with details

**Comment by mbonsma** [comment]
Feel free to update these still, I'm just merging so I can post the links on the website.

**Comment by linamnt** [comment]
A lot of the challenges aren't necessarily translatable in Python without introducing new pandas methods. Probably going to rework the challenges and what they ask for.

**Pull request merged**
